Data Analysis --> Numpy (Numerical Python) 
Pandas along with Data Visualization (Matplotlib)
Pandas -->Panel Data (Data Cleaning,Data Transformations -->Powerful tool)

In [ ]:
#Installing Pandas
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 66.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.2 in /home/workspace/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 96.3 MB/s eta 0:00:0000:0100:01
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.3/508.3 KB 66.8 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.2/348.2 KB 49.2 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /home/workspace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [3]:
import pandas as pd

#Series --> 1 Dimensional data representation
#DataFrame --> 2 Dimensional data representation (table -->rows,columns)

In [13]:
marks = [45,65,23,45]
d = pd.Series(marks)
print(d)
print(type(d))
print(d.dtype)
print(d.ndim)
print(d.shape)
print(d.size)
print(type(d.dtypes))
print(d.index)

0    45
1    65
2    23
3    45
dtype: int64
<class 'pandas.core.series.Series'>
int64
1
(4,)
4
<class 'numpy.dtypes.Int64DType'>
RangeIndex(start=0, stop=4, step=1)

In [25]:
data = {'names':['AAA','PFS','JFS','DA','DS'],
'ids':[12,43,56,67]}
h = pd.Series(data)
print(h)
print(h.index)
print(h.dtype)
print(h['names'])
print(h['ids'])
print(h['names'][2])
print(h['ids'][:2])
print(h['ids'])

names    [AAA, PFS, JFS, DA, DS]
ids             [12, 43, 56, 67]
dtype: object
Index(['names', 'ids'], dtype='object')
object
['AAA', 'PFS', 'JFS', 'DA', 'DS']
[12, 43, 56, 67]
JFS
[12, 43]
[12, 43, 56, 67]

In [35]:
data = 6
g = pd.Series(data)
print(g)
h = pd.Series(data,index =['rank'])
print(h)
print(h.dtype)

0    6
dtype: int64
rank    6
dtype: int64
int64

In [32]:
name = "Codegnan"
g = pd.Series(name)
print(g)
g = pd.Series(name,index=['company'])
print(g)

0    Codegnan
dtype: object
company    Codegnan
dtype: object

In [44]:
#DataFrame -->2 Dimensional representation (table format)
marks = [45,65,23,45]
h = pd.DataFrame(marks)
print(h) #default index and column as rangeindex
print(h.index);print(h.columns)
k = pd.DataFrame(marks,columns =['Marks']) #modifying the column
print(k)
print(k.shape)
print(k.size)
print(k.ndim)

    0
0  45
1  65
2  23
3  45
RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=1, step=1)
   Marks
0     45
1     65
2     23
3     45
(4, 1)
4
2

In [51]:
details = {'Products':['Mobiles','Laptops','Earphones','Headphones'],
'Sales':[20000,10000,21000,50000],
'Stock':[10,5,35,55],
}
h = pd.DataFrame(details)
print(h)
print(h.shape)
print(h.size)
print(h.ndim)
print(type(h))
print(h.dtypes) #returns dtype of each column
print(h.select_dtypes('int'))

     Products  Sales  Stock
0     Mobiles  20000     10
1     Laptops  10000      5
2   Earphones  21000     35
3  Headphones  50000     55
(4, 3)
12
2
<class 'pandas.core.frame.DataFrame'>
Products    object
Sales        int64
Stock        int64
dtype: object
   Sales  Stock
0  20000     10
1  10000      5
2  21000     35
3  50000     55

In [52]:
#to access columns
print(h.columns)

Index(['Products', 'Sales', 'Stock'], dtype='object')

In [55]:
h['Products']
#Group of columns
h[['Products','Sales']]

     Products  Sales
0     Mobiles  20000
1     Laptops  10000
2   Earphones  21000
3  Headphones  50000

In [58]:
h[['Products','Sales']];
h.Products

0       Mobiles
1       Laptops
2     Earphones
3    Headphones
Name: Products, dtype: object

In [59]:
#Access rowwise data ->index -->loc(),iloc()
h.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(h.loc[0]) #locating index values (Selecting by labels)
print(h.loc[0]['Products'])
print(h.loc[0][['Sales','Stock']])
print(h.loc[[2,0]][['Products','Stock']])
print(h.loc[1,'Stock'])

Products    Mobiles
Sales         20000
Stock            10
Name: 0, dtype: object
Mobiles
Sales    20000
Stock       10
Name: 0, dtype: object
    Products  Stock
2  Earphones     35
0    Mobiles     10
5

In [71]:
h

     Products  Sales  Stock
0     Mobiles  20000     10
1     Laptops  10000      5
2   Earphones  21000     35
3  Headphones  50000     55

In [ ]:
#iloc() -->selecting by position
print(h.index) #As its default integer index both loc(),iloc()
print(h.iloc[0])
print(h.iloc[[2,3]])
print(h.iloc[[2,3]][['Stock','Products']])

RangeIndex(start=0, stop=4, step=1)
Products    Mobiles
Sales         20000
Stock            10
Name: 0, dtype: object
     Products  Sales  Stock
2   Earphones  21000     35
3  Headphones  50000     55
   Stock    Products
2     35   Earphones
3     55  Headphones

In [ ]:
print(h.info()) #Complete information about dataframe
#Summary of the dataframe -->Descrptive Statitical info
print(h.describe())
print(h.describe(include='object')) #for object type -->count,unique
#top --> most repeating value,freq -->count of most repeating value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Products  4 non-null      object
 1   Sales     4 non-null      int64
 2   Stock     4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None
              Sales      Stock
count      4.000000   4.000000
mean   25250.000000  26.250000
std    17231.270025  23.228933
min    10000.000000   5.000000
25%    17500.000000   8.750000
50%    20500.000000  22.500000
75%    28250.000000  40.000000
max    50000.000000  55.000000
       Products
count         4
unique        4
top     Mobiles
freq          1

In [77]:
#Change the datatype of column
h['Sales'] = h['Sales'].astype('float')
print(h['Sales'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: Sales
Non-Null Count  Dtype
--------------  -----
4 non-null      float64
dtypes: float64(1)
memory usage: 160.0 bytes
None

In [81]:
h

     Products    Sales  Stock
0     Mobiles  20000.0     10
1     Laptops  10000.0      5
2   Earphones  21000.0     35
3  Headphones  50000.0     55

In [82]:
pd.read_csv("Products.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Products.csv'

In [79]:
#groupby()
h.groupby('Products')['Sales'].mean()

Products
Earphones     21000.0
Headphones    50000.0
Laptops       10000.0
Mobiles       20000.0
Name: Sales, dtype: float64